//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: account.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetLoginMsg")]
  public partial class RetLoginMsg : global::ProtoBuf.IExtensible
  {
    public RetLoginMsg() {}
    
    private string _Account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private byte[] _SessionKey = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SessionKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] SessionKey
    {
      get { return _SessionKey; }
      set { _SessionKey = value; }
    }
    private string _Address = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private string _Key = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}