//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gateway.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqHttpArgData")]
  public partial class ReqHttpArgData : global::ProtoBuf.IExtensible
  {
    public ReqHttpArgData() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.ReqHttpArgData.KeyVal> _Args = new global::System.Collections.Generic.List<usercmd.ReqHttpArgData.KeyVal>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.ReqHttpArgData.KeyVal> Args
    {
      get { return _Args; }
    }
  
    private uint _Cmd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Cmd
    {
      get { return _Cmd; }
      set { _Cmd = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyVal")]
  public partial class KeyVal : global::ProtoBuf.IExtensible
  {
    public KeyVal() {}
    
    private string _Key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private string _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqServiceReg")]
  public partial class ReqServiceReg : global::ProtoBuf.IExtensible
  {
    public ReqServiceReg() {}
    
    private string _Key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private uint _ServerType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ServerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ServerType
    {
      get { return _ServerType; }
      set { _ServerType = value; }
    }
    private uint _ServerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private string _Address = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private string _InAddress = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"InAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string InAddress
    {
      get { return _InAddress; }
      set { _InAddress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetServiceReg")]
  public partial class RetServiceReg : global::ProtoBuf.IExtensible
  {
    public RetServiceReg() {}
    
    private uint _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _NodeIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"NodeIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> NodeIds
    {
      get { return _NodeIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetServiceAdd")]
  public partial class RetServiceAdd : global::ProtoBuf.IExtensible
  {
    public RetServiceAdd() {}
    
    private uint _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Address;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private uint _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetServiceLeave")]
  public partial class RetServiceLeave : global::ProtoBuf.IExtensible
  {
    public RetServiceLeave() {}
    
    private uint _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private uint _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqUserLogin")]
  public partial class ReqUserLogin : global::ProtoBuf.IExtensible
  {
    public ReqUserLogin() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _Location;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Location
    {
      get { return _Location; }
      set { _Location = value; }
    }
    private uint _CNet;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"CNet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CNet
    {
      get { return _CNet; }
      set { _CNet = value; }
    }
    private uint _Money = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private uint _MaxLevel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"MaxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MaxLevel
    {
      get { return _MaxLevel; }
      set { _MaxLevel = value; }
    }
    private uint _Credit = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Credit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Credit
    {
      get { return _Credit; }
      set { _Credit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqS2CNoticeBatch")]
  public partial class ReqS2CNoticeBatch : global::ProtoBuf.IExtensible
  {
    public ReqS2CNoticeBatch() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _UserIds = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"UserIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> UserIds
    {
      get { return _UserIds; }
    }
  
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private uint _Flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqServiceHeartbeat")]
  public partial class ReqServiceHeartbeat : global::ProtoBuf.IExtensible
  {
    public ReqServiceHeartbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqFullNotice")]
  public partial class ReqFullNotice : global::ProtoBuf.IExtensible
  {
    public ReqFullNotice() {}
    
    private uint _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private uint _Flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GatewayCmd")]
    public enum GatewayCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceReg", Value=1)]
      ServiceReg = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceAdd", Value=3)]
      ServiceAdd = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceLeave", Value=4)]
      ServiceLeave = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserLogin", Value=15)]
      UserLogin = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2CNotice", Value=21)]
      S2CNotice = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendNotice", Value=22)]
      SendNotice = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2CNoticeBatch", Value=23)]
      S2CNoticeBatch = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServiceHeartbeat", Value=29)]
      ServiceHeartbeat = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FullNotice", Value=30)]
      FullNotice = 30
    }
  
}