//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: team.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqTeamLogin")]
  public partial class ReqTeamLogin : global::ProtoBuf.IExtensible
  {
    public ReqTeamLogin() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private string _ClientVer = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ClientVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ClientVer
    {
      get { return _ClientVer; }
      set { _ClientVer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetTeamLogin")]
  public partial class RetTeamLogin : global::ProtoBuf.IExtensible
  {
    public RetTeamLogin() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private uint _RemTime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RemTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RemTime
    {
      get { return _RemTime; }
      set { _RemTime = value; }
    }
    private bool _Season = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Season", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Season
    {
      get { return _Season; }
      set { _Season = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartGame")]
  public partial class ReqStartGame : global::ProtoBuf.IExtensible
  {
    public ReqStartGame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetStartGame")]
  public partial class RetStartGame : global::ProtoBuf.IExtensible
  {
    public RetStartGame() {}
    
    private string _Address;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private string _Key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private string _AddressAll = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"AddressAll", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AddressAll
    {
      get { return _AddressAll; }
      set { _AddressAll = value; }
    }
    private bool _Delay = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Delay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Delay
    {
      get { return _Delay; }
      set { _Delay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetErrorCmd")]
  public partial class RetErrorCmd : global::ProtoBuf.IExtensible
  {
    public RetErrorCmd() {}
    
    private uint _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private uint _Params = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Params
    {
      get { return _Params; }
      set { _Params = value; }
    }
    private string _JsonParam = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"JsonParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string JsonParam
    {
      get { return _JsonParam; }
      set { _JsonParam = value; }
    }
    private string _ErrDesc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ErrDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrDesc
    {
      get { return _ErrDesc; }
      set { _ErrDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenTeamBox")]
  public partial class OpenTeamBox : global::ProtoBuf.IExtensible
  {
    public OpenTeamBox() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecvTeamBox")]
  public partial class RecvTeamBox : global::ProtoBuf.IExtensible
  {
    public RecvTeamBox() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.RecvTeamBox.ObjNode> _Objs = new global::System.Collections.Generic.List<usercmd.RecvTeamBox.ObjNode>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Objs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.RecvTeamBox.ObjNode> Objs
    {
      get { return _Objs; }
    }
  
    private ulong _UserId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Account = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjNode")]
  public partial class ObjNode : global::ProtoBuf.IExtensible
  {
    public ObjNode() {}
    
    private uint _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private uint _Num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAchieve")]
  public partial class GetAchieve : global::ProtoBuf.IExtensible
  {
    public GetAchieve() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _Achieves = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Achieves", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> Achieves
    {
      get { return _Achieves; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInvDBrush")]
  public partial class GetInvDBrush : global::ProtoBuf.IExtensible
  {
    public GetInvDBrush() {}
    
    private ulong _UserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetPushMsgCmd")]
  public partial class RetPushMsgCmd : global::ProtoBuf.IExtensible
  {
    public RetPushMsgCmd() {}
    
    private uint _MsgType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MsgType
    {
      get { return _MsgType; }
      set { _MsgType = value; }
    }
    private usercmd.RetPushMsgCmd.NewbieComm _NComm = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NComm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.RetPushMsgCmd.NewbieComm NComm
    {
      get { return _NComm; }
      set { _NComm = value; }
    }
    private usercmd.RetPushMsgCmd.FollowUser _FUser = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"FUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.RetPushMsgCmd.FollowUser FUser
    {
      get { return _FUser; }
      set { _FUser = value; }
    }
    private usercmd.OpenTeamBox _OBox = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OBox", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.OpenTeamBox OBox
    {
      get { return _OBox; }
      set { _OBox = value; }
    }
    private usercmd.RecvTeamBox _RBox = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"RBox", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.RecvTeamBox RBox
    {
      get { return _RBox; }
      set { _RBox = value; }
    }
    private usercmd.GetAchieve _GAch = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"GAch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.GetAchieve GAch
    {
      get { return _GAch; }
      set { _GAch = value; }
    }
    private usercmd.GetInvDBrush _GDBrush = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"GDBrush", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.GetInvDBrush GDBrush
    {
      get { return _GDBrush; }
      set { _GDBrush = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewbieComm")]
  public partial class NewbieComm : global::ProtoBuf.IExtensible
  {
    public NewbieComm() {}
    
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _CType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CType
    {
      get { return _CType; }
      set { _CType = value; }
    }
    private uint _Flowers;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Flowers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Flowers
    {
      get { return _Flowers; }
      set { _Flowers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FollowUser")]
  public partial class FollowUser : global::ProtoBuf.IExtensible
  {
    public FollowUser() {}
    
    private ulong _UID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UID
    {
      get { return _UID; }
      set { _UID = value; }
    }
    private string _Account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private uint _Sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private uint _FollowType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"FollowType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FollowType
    {
      get { return _FollowType; }
      set { _FollowType = value; }
    }
    private uint _Icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _PassIcon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PassIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PassIcon
    {
      get { return _PassIcon; }
      set { _PassIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamCmd")]
    public enum TeamCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1)]
      Login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartGame", Value=6)]
      StartGame = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorCmd", Value=9)]
      ErrorCmd = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendNotice", Value=12)]
      SendNotice = 12
    }
  
}